install.packages("shiny")
install.packages("plotly")
install.packages("reshape2")
install.packages("gplots")
install.packages("stringr")
install.packages("ggdendro")
install.packages("gridBase")
install.packages("RColorBrewer")
install.packages("rvg")
install.packages("ggplot2")
install.packages("dbplyr")
install.packages("dplyr")
install.packages("proto")
install.packages("gsubfn")
install.packages("sqldf")
install.packages("slam")
install.packages("RPostgreSQL")
install.packages("foreach")

#install.packages("d3heatmap")
#install.packages("ggiraph")

# Install Bioconductor and BioC packages

source("http://bioconductor.org/biocLite.R")
biocLite()
biocLite("ggbio")
biocLite("GenomicRanges")
biocLite("TxDb.Hsapiens.UCSC.hg38.knownGene")
biocLite("chromPlot")
biocLite("karyoploteR")
